Added Console Application and Container helper
gmo/common pull request #6
Opened 2017-06-30 00:11 UTC by CarsonF

adapted from console library which is being deprecated.

This one references a PSR-11 container. So the pimple/silex container will have to be adapted to that. We can use this package for that: https://github.com/GromNaN/pimple-interop

2017-07-13 19:16 UTC, mikegillis677 requested changes

2017-07-13 19:16 UTC, mikegillis677 commented on src/Console/Application.php
> +        $this->projectDir = $dir;
Can we get a `file_exists($dir) && is_dir($dir)` check here?

2017-07-14 14:24 UTC, CarsonF commented on src/Console/Application.php
> +        $this->projectDir = $dir;
Done

2017-07-14 14:55 UTC, mikegillis677 approved these changes

2017-07-14 15:16 UTC, merged